[ui]
step_mode = false

[questioning]
ask_user_cdqs = false
ask_user_ckpt = false
computer_can_lie = true

[algorithm]
assume_lying = true
checkpoint_frequency = 4
test_grid = "test_grids/1.txt"

[logging]
logging_level = "debug"