[ui]
step_mode = false

[questioning]
ask_user_cdqs = false
ask_user_ckpt = false
computer_can_lie = true

[algorithm]
assume_lying = true
checkpoint_frequency = 20


[logging]
logging_level = "info"

