[ui]
step_mode = false

[questioning]
ask_user_cdqs = true
ask_user_ckpt = true
computer_can_lie = true
checkpointing_method = "repeat" # dyl for did you lie vs. repeat

[algorithm]
assume_lying = true
checkpoint_frequency = 4
test_grid = "test_grids/5.txt"

[logging]
logging_level = "debug"