[ui]
step_mode = false

[questioning]
ask_user_cdqs = false
ask_user_ckpt = false
computer_can_lie = false

[algorithm]
assume_lying = false
checkpoint_frequency = 4

[logging]
logging_level = "debug"

